package fr.lip6.meta.tracerecorder.listner;


/**
 * The {@link SequenceListener} knows that the sequence is divided into two parts: 
 * 	- the initialization with the serialization of all involved models and then
 *  - the sequence derived from the observation of the user
 * 
 * Implementations should avoid considering initialization actions as generated by the users ;)
 * 
 * @author Marcos Aurélio
 */
public interface SequenceListener {

	void sendAction(String action);
	void initializationFinished();
		
}
